/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CodigoFonte.UserDAO;
import CodigoFonte.users;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luzk
 */
public class FormLogin extends javax.swing.JFrame {
         Classe_hash h = new Classe_hash();
         UserDAO userDAO;
         private users users;
    /**
     * Creates new form FormLogin
     * @param userDAO
     */
    public FormLogin(UserDAO userDAO) {
        initComponents();
        this.userDAO = userDAO;
    }
    
    FormLogin(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtuser.setBackground(new java.awt.Color(226, 226, 226));
        txtuser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtuser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 61, 214, 35));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Entrar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 207, 141, 38));

        lblNome.setBackground(new java.awt.Color(0, 0, 0));
        lblNome.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(69, 69, 69));
        lblNome.setText("Senha");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 109, -1, -1));

        lblNome1.setBackground(new java.awt.Color(0, 0, 0));
        lblNome1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(69, 69, 69));
        lblNome1.setText("Usuário");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 29, -1, -1));

        txtsenha.setBackground(new java.awt.Color(226, 226, 226));
        txtsenha.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtsenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 141, 214, 36));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario, senha;
        int flag=0;
        usuario = txtuser.getText();
        senha = txtsenha.getText();
        ArrayList<users> arrUsers = userDAO.listar();
        int num = arrUsers.size();
        for (int i = 0; i < num; i++) {
            if(usuario.equals(arrUsers.get(i).getLogin())){
                senha = h.makeHash(senha);
                if(senha.equals(arrUsers.get(i).getSenha())){
                    System.out.println("Acesso Liberado");
                    TelaAcesso sis = new TelaAcesso();
                    sis.setVisible(true); // abrindo o formSistema
                    this.limpaCampos();
                    this.dispose();
                    flag = 1;
                    break;
                }else{
                    JOptionPane.showMessageDialog(null,"Senha incorreta!");
                    flag = 1;
                    break;
                }
            }
        }if(flag==0){
            JOptionPane.showMessageDialog(null,"Usuario não existe!");
            new TelaPrincipal().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    public void limpaCampos(){
        txtuser.setText("");
        txtsenha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
