/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CodigoFonte.hqs;
import CodigoFonte.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaExcluir extends javax.swing.JInternalFrame {

    private UsuarioDAO usuarioDAO;
    private hqs hqs;
    private int linha;

    /**
     * Creates new form telaConsulta
     * @param usuarioDAO
     */
    public TelaExcluir(UsuarioDAO usuarioDAO) {
        initComponents();
        this.usuarioDAO = usuarioDAO;
        hqs = new hqs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblIdade = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        lblCPF3 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblCPF2 = new javax.swing.JLabel();
        txtPaginas = new javax.swing.JTextField();
        txtVolume = new javax.swing.JTextField();
        lblCPF1 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        lblcapa1 = new javax.swing.JLabel();
        txtfilename1 = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tabelaConsulta.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Editora", "Autor", "Paginas", "Volume", "Genero", "Capa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsulta.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaConsulta);
        if (tabelaConsulta.getColumnModel().getColumnCount() > 0) {
            tabelaConsulta.getColumnModel().getColumn(0).setResizable(false);
            tabelaConsulta.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaConsulta.getColumnModel().getColumn(1).setResizable(false);
            tabelaConsulta.getColumnModel().getColumn(2).setResizable(false);
            tabelaConsulta.getColumnModel().getColumn(3).setResizable(false);
            tabelaConsulta.getColumnModel().getColumn(4).setResizable(false);
            tabelaConsulta.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(102, 102, 102));
        lblNome.setText("Titulo");

        txtTitulo.setBackground(new java.awt.Color(226, 226, 226));
        txtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtTitulo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtTitulo.setEnabled(false);
        txtTitulo.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lblIdade.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(102, 102, 102));
        lblIdade.setText("Editora");

        txtEditora.setBackground(new java.awt.Color(226, 226, 226));
        txtEditora.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtEditora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtEditora.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtEditora.setEnabled(false);
        txtEditora.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF3.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF3.setText("Autor");

        txtAutor.setBackground(new java.awt.Color(226, 226, 226));
        txtAutor.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtAutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtAutor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtAutor.setEnabled(false);
        txtAutor.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF2.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF2.setText("Paginas");

        txtPaginas.setBackground(new java.awt.Color(226, 226, 226));
        txtPaginas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtPaginas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtPaginas.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtPaginas.setEnabled(false);
        txtPaginas.setSelectionColor(new java.awt.Color(51, 51, 51));

        txtVolume.setBackground(new java.awt.Color(226, 226, 226));
        txtVolume.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtVolume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtVolume.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtVolume.setEnabled(false);
        txtVolume.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF1.setText("Volume");

        txtGenero.setBackground(new java.awt.Color(226, 226, 226));
        txtGenero.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtGenero.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtGenero.setEnabled(false);
        txtGenero.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF.setText("Genero");

        btnExcluir.setBackground(new java.awt.Color(51, 204, 255));
        btnExcluir.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblcapa1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblcapa1.setForeground(new java.awt.Color(102, 102, 102));
        lblcapa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcapa1.setText("Capa");

        txtfilename1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtfilename1.setForeground(new java.awt.Color(255, 255, 255));
        txtfilename1.setBorder(null);
        txtfilename1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtfilename1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtfilename1.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtfilename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilename1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblIdade)
                            .addComponent(lblCPF)
                            .addComponent(lblCPF2)
                            .addComponent(lblCPF3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCPF1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfilename1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF3)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF2)
                            .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF1)
                            .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfilename1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        atualizaTabela();

    }//GEN-LAST:event_formInternalFrameActivated

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        // TODO add your handling code here:

        linha = tabelaConsulta.getSelectedRow();
        copiaDadosParaOsCampos();
        carregacapa();
        btnExcluir.setEnabled(true);

    }//GEN-LAST:event_tabelaConsultaMouseClicked
    public void copiaDadosParaOsCampos() {
        txtTitulo.setText((String) tabelaConsulta.getValueAt(linha, 1));
        txtEditora.setText((String) tabelaConsulta.getValueAt(linha, 2));
        txtAutor.setText((String) tabelaConsulta.getValueAt(linha, 3));
        txtPaginas.setText(Integer.toString((int) tabelaConsulta.getValueAt(linha, 4)));
        txtVolume.setText(Integer.toString((int) tabelaConsulta.getValueAt(linha, 5)));  
        txtGenero.setText((String) tabelaConsulta.getValueAt(linha, 6));  
    }


    private void tabelaConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabelaConsultaMouseEntered

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Você deseja excluir estas informações?");
        if (input == 0) {
            hqs.setId((int) tabelaConsulta.getValueAt(linha, 0));
            usuarioDAO.remover(hqs);
            atualizaTabela();
            limpaCampos();
            btnExcluir.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Dado excluído com Sucesso!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtfilename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilename1ActionPerformed

    public void atualizaTabela() {
        DefaultTableModel model = (DefaultTableModel) tabelaConsulta.getModel();
        ArrayList<hqs> arrConsulta = usuarioDAO.listar();
        int numRows = arrConsulta.size();
        model.setNumRows(numRows);

        for (int i = 0; i < numRows; i++) {
            model.setValueAt(arrConsulta.get(i).getId(), i, 0);
            model.setValueAt(arrConsulta.get(i).getTitulo(), i, 1);
            model.setValueAt(arrConsulta.get(i).getEditora(), i, 2);
            model.setValueAt(arrConsulta.get(i).getAutor(), i, 3);
            model.setValueAt(arrConsulta.get(i).getPaginas(), i, 4);
            model.setValueAt(arrConsulta.get(i).getVolume(), i, 5);
            model.setValueAt(arrConsulta.get(i).getGenero(), i, 6);
            model.setValueAt(arrConsulta.get(i).getCapa(), i, 7);
        }
    }

    public void limpaCampos() {
        txtTitulo.setText("");
        txtEditora.setText("");
        txtAutor.setText("");
        txtPaginas.setText("");
        txtVolume.setText("");
        txtGenero.setText("");
        lblcapa1.setIcon(null);
    }
    
    public void carregacapa() {
        String filename = (String) tabelaConsulta.getValueAt(linha, 7);
        ImageIcon icon = new ImageIcon(filename); 
        lblcapa1.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblCPF2;
    private javax.swing.JLabel lblCPF3;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblcapa1;
    private javax.swing.JTable tabelaConsulta;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVolume;
    private javax.swing.JTextField txtfilename1;
    // End of variables declaration//GEN-END:variables
}
