/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import CodigoFonte.DAOFactory;
import CodigoFonte.UsuarioDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author Luzk
 */
public class TelaAcesso extends javax.swing.JFrame {
    DAOFactory factory;
    UsuarioDAO usuarioDAO;
    TelaCadastrar telaCadastrar;
    TelaConsulta telaConsulta;
    TelaAlterar telaAlterar;
    TelaExcluir telaExcluir;
    TelaPrincipal telaprincipal;

    /**
     * Creates new form TelaAcesso
     */
    public TelaAcesso() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        factory = new DAOFactory();
        this.usuarioDAO = factory.CreateDAO();
        telaCadastrar = new TelaCadastrar(usuarioDAO);
        telaConsulta = new TelaConsulta(usuarioDAO);
        telaAlterar = new TelaAlterar(usuarioDAO);
        telaExcluir = new TelaExcluir(usuarioDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        itemCadastrarUsuario = new javax.swing.JMenuItem();
        itemConsulta = new javax.swing.JMenuItem();
        itemAlterar = new javax.swing.JMenuItem();
        itemExcluir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        painelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/サイファー by ナダレ main.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        painelPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(0, 729, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel1.getAccessibleContext().setAccessibleName("label");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        menuArquivo.setBackground(new java.awt.Color(255, 255, 255));
        menuArquivo.setForeground(new java.awt.Color(51, 51, 51));
        menuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/page.png"))); // NOI18N
        menuArquivo.setText("Arquivo");
        menuArquivo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        itemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemSair.setBackground(new java.awt.Color(255, 255, 255));
        itemSair.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(51, 51, 51));
        itemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/door_out.png"))); // NOI18N
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemSair);

        jMenuBar1.add(menuArquivo);

        menuCadastro.setBackground(new java.awt.Color(255, 255, 255));
        menuCadastro.setForeground(new java.awt.Color(51, 51, 51));
        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/group.png"))); // NOI18N
        menuCadastro.setText("Cadastro");

        itemCadastrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        itemCadastrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        itemCadastrarUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        itemCadastrarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        itemCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_add.png"))); // NOI18N
        itemCadastrarUsuario.setText("Cadastrar HQ");
        itemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastrarUsuario);

        itemConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        itemConsulta.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        itemConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zoom.png"))); // NOI18N
        itemConsulta.setText("Consulta");
        itemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemConsulta);

        itemAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        itemAlterar.setBackground(new java.awt.Color(255, 255, 255));
        itemAlterar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        itemAlterar.setForeground(new java.awt.Color(51, 51, 51));
        itemAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_edit.png"))); // NOI18N
        itemAlterar.setText("Alterar HQ");
        itemAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlterarActionPerformed(evt);
            }
        });
        menuCadastro.add(itemAlterar);

        itemExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        itemExcluir.setBackground(new java.awt.Color(255, 255, 255));
        itemExcluir.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        itemExcluir.setForeground(new java.awt.Color(51, 51, 51));
        itemExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_delete.png"))); // NOI18N
        itemExcluir.setText("Excluir HQ");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        menuCadastro.add(itemExcluir);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        painelPrincipal.add(telaCadastrar);
        telaCadastrar.setVisible(true);
    }//GEN-LAST:event_itemCadastrarUsuarioActionPerformed

    private void itemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaActionPerformed

        // TODO add your handling code here:

        painelPrincipal.add(telaConsulta);
        telaConsulta.setVisible(true);

    }//GEN-LAST:event_itemConsultaActionPerformed

    private void itemAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlterarActionPerformed
        // TODO add your handling code here:

        painelPrincipal.add(telaAlterar);
        telaAlterar.setVisible(true);
    }//GEN-LAST:event_itemAlterarActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        // TODO add your handling code here:

        painelPrincipal.add(telaExcluir);
        telaExcluir.setVisible(true);
    }//GEN-LAST:event_itemExcluirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAlterar;
    private javax.swing.JMenuItem itemCadastrarUsuario;
    private javax.swing.JMenuItem itemConsulta;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables

}