/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CodigoFonte.hqs;
import CodigoFonte.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class TelaConsulta extends javax.swing.JInternalFrame {

    UsuarioDAO usuarioDAO;
    private int linha;

    /**
     * Creates new form telaConsulta
     * @param usuarioDAO
     */
    public TelaConsulta(UsuarioDAO usuarioDAO) {
        initComponents();
        this.usuarioDAO = usuarioDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcapa1 = new javax.swing.JLabel();
        txtfilename1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        lblcapa2 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        lblcapa1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblcapa1.setForeground(new java.awt.Color(102, 102, 102));
        lblcapa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcapa1.setText("Capa");

        txtfilename1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtfilename1.setForeground(new java.awt.Color(255, 255, 255));
        txtfilename1.setBorder(null);
        txtfilename1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtfilename1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtfilename1.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtfilename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilename1ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(600, 465));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tabelaConsulta.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Editora", "Autor", "Paginas", "Volume", "Genero", "Capa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsulta.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaConsulta);
        if (tabelaConsulta.getColumnModel().getColumnCount() > 0) {
            tabelaConsulta.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaConsulta.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        lblcapa2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblcapa2.setForeground(new java.awt.Color(102, 102, 102));
        lblcapa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcapa2.setText("Capa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblcapa2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcapa2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFechar.setBackground(new java.awt.Color(51, 204, 255));
        btnFechar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setBorder(null);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 542, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        atualizaTabela();

    }//GEN-LAST:event_formInternalFrameActivated

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtfilename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilename1ActionPerformed

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        // TODO add your handling code here:
        linha = tabelaConsulta.getSelectedRow(); 
        carregacapa();
    }//GEN-LAST:event_tabelaConsultaMouseClicked
    public void atualizaTabela() {
        DefaultTableModel model = (DefaultTableModel) tabelaConsulta.getModel();
        ArrayList<hqs> arrConsulta = usuarioDAO.listar();
        int numRows = arrConsulta.size();
        model.setNumRows(numRows);

        for (int i = 0; i < numRows; i++) {
            model.setValueAt(arrConsulta.get(i).getId(), i, 0);
            model.setValueAt(arrConsulta.get(i).getTitulo(), i, 1);
            model.setValueAt(arrConsulta.get(i).getEditora(), i, 2);
            model.setValueAt(arrConsulta.get(i).getAutor(), i, 3);
            model.setValueAt(arrConsulta.get(i).getPaginas(), i, 4);
            model.setValueAt(arrConsulta.get(i).getVolume(), i, 5);
            model.setValueAt(arrConsulta.get(i).getGenero(), i, 6);
            model.setValueAt(arrConsulta.get(i).getCapa(), i, 7);
        }
    }
    
    public void carregacapa(){
        String filename = (String)tabelaConsulta.getValueAt(linha, 7);
        ImageIcon icon = new ImageIcon(filename); 
        lblcapa2.setIcon(icon);
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcapa1;
    private javax.swing.JLabel lblcapa2;
    private javax.swing.JTable tabelaConsulta;
    private javax.swing.JTextField txtfilename1;
    // End of variables declaration//GEN-END:variables
}
