/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CodigoFonte.hqs;
import CodigoFonte.UsuarioDAO;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaAlterar extends javax.swing.JInternalFrame {
    private UsuarioDAO usuarioDAO;
    private hqs hqs;
    private int linha;

    /**
     * Creates new form telaConsulta
     * @param usuarioDAO
     */
    public TelaAlterar(UsuarioDAO usuarioDAO) {
        initComponents();
        this.usuarioDAO = usuarioDAO;
        hqs = new hqs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        lblcapa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtfilename = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblCPF1 = new javax.swing.JLabel();
        txtVolume = new javax.swing.JTextField();
        lblCPF2 = new javax.swing.JLabel();
        txtPaginas = new javax.swing.JTextField();
        lblCPF3 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaConsulta = new javax.swing.JTable();
        lblcapa1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtfilename1 = new javax.swing.JTextField();

        lblcapa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblcapa.setForeground(new java.awt.Color(102, 102, 102));
        lblcapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcapa.setText("Capa");

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adicionar Capa");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtfilename.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtfilename.setForeground(new java.awt.Color(255, 255, 255));
        txtfilename.setBorder(null);
        txtfilename.setCaretColor(new java.awt.Color(255, 255, 255));
        txtfilename.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtfilename.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtfilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilenameActionPerformed(evt);
            }
        });

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(102, 102, 102));
        lblNome.setText("Titulo");

        lblIdade.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(102, 102, 102));
        lblIdade.setText("Editora");

        lblCPF.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF.setText("Genero");

        txtTitulo.setBackground(new java.awt.Color(226, 226, 226));
        txtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtTitulo.setEnabled(false);
        txtTitulo.setSelectionColor(new java.awt.Color(51, 51, 51));
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtEditora.setBackground(new java.awt.Color(226, 226, 226));
        txtEditora.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtEditora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtEditora.setEnabled(false);
        txtEditora.setSelectionColor(new java.awt.Color(51, 51, 51));

        txtGenero.setBackground(new java.awt.Color(226, 226, 226));
        txtGenero.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtGenero.setEnabled(false);
        txtGenero.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF1.setText("Volume");

        txtVolume.setBackground(new java.awt.Color(226, 226, 226));
        txtVolume.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtVolume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtVolume.setEnabled(false);
        txtVolume.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF2.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF2.setText("Paginas");

        txtPaginas.setBackground(new java.awt.Color(226, 226, 226));
        txtPaginas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtPaginas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtPaginas.setEnabled(false);
        txtPaginas.setSelectionColor(new java.awt.Color(51, 51, 51));

        lblCPF3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblCPF3.setForeground(new java.awt.Color(102, 102, 102));
        lblCPF3.setText("Autor");

        txtAutor.setBackground(new java.awt.Color(226, 226, 226));
        txtAutor.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtAutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 226, 226), 2, true));
        txtAutor.setEnabled(false);
        txtAutor.setSelectionColor(new java.awt.Color(51, 51, 51));

        btnAlterar.setBackground(new java.awt.Color(51, 204, 255));
        btnAlterar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(null);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        tabelaConsulta.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        tabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Editora", "Autor", "Paginas", "Volume", "Genero", "Capa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaConsulta.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelaConsultaMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaConsulta);
        if (tabelaConsulta.getColumnModel().getColumnCount() > 0) {
            tabelaConsulta.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaConsulta.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        lblcapa1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblcapa1.setForeground(new java.awt.Color(102, 102, 102));
        lblcapa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcapa1.setText("Capa");

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Alterar Capa");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtfilename1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtfilename1.setForeground(new java.awt.Color(255, 255, 255));
        txtfilename1.setBorder(null);
        txtfilename1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtfilename1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtfilename1.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtfilename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilename1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblIdade)
                                    .addComponent(lblCPF3)
                                    .addComponent(lblCPF2)
                                    .addComponent(lblCPF))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblCPF1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(lblcapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtfilename1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(21, 21, 21)
                        .addComponent(lblIdade)
                        .addGap(21, 21, 21)
                        .addComponent(lblCPF3)
                        .addGap(21, 21, 21)
                        .addComponent(lblCPF2)
                        .addGap(21, 21, 21)
                        .addComponent(lblCPF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPF1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtfilename1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        atualizaTabela();
        habilitaCampos();
        linha = tabelaConsulta.getSelectedRow();
        copiaDadosParaOsCampos();
    }//GEN-LAST:event_formInternalFrameActivated
    public void copiaDadosUsuario(){
        hqs.setId((int) tabelaConsulta.getValueAt(linha, 0));
        hqs.setTitulo(txtTitulo.getText());
        hqs.setEditora(txtEditora.getText());
        hqs.setAutor(txtAutor.getText());
        hqs.setPaginas(Integer.parseInt(txtPaginas.getText()));
        hqs.setVolume(Integer.parseInt(txtVolume.getText()));
        hqs.setGenero(txtGenero.getText());
        hqs.setCapa(txtfilename1.getText());
    }
    public void copiaDadosParaOsCampos() {      
        txtTitulo.setText((String) tabelaConsulta.getValueAt(linha, 1));
        txtEditora.setText((String) tabelaConsulta.getValueAt(linha, 2));
        txtAutor.setText((String) tabelaConsulta.getValueAt(linha, 3));
        txtPaginas.setText(Integer.toString((int) tabelaConsulta.getValueAt(linha, 4)));
        txtVolume.setText(Integer.toString((int) tabelaConsulta.getValueAt(linha, 5)));  
        txtGenero.setText((String) tabelaConsulta.getValueAt(linha, 6));
        txtfilename1.setText((String) tabelaConsulta.getValueAt(linha, 7));
    }

    public void habilitaCampos() {
        txtTitulo.setEnabled(true);
        txtEditora.setEnabled(true);
        txtAutor.setEnabled(true);
        txtPaginas.setEnabled(true);
        txtVolume.setEnabled(true);
        txtGenero.setEnabled(true);
        btnAlterar.setEnabled(true);
    }

    public void desabilitaCampos() {
        txtTitulo.setEnabled(false);
        txtEditora.setEnabled(false);
        txtAutor.setEnabled(false);
        txtPaginas.setEnabled(false);
        txtVolume.setEnabled(false);
        txtGenero.setEnabled(false);
        btnAlterar.setEnabled(false);
        lblcapa1.setIcon(null);
    }

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        copiaDadosUsuario();
        usuarioDAO.atualizar(hqs);
        JOptionPane.showMessageDialog(null, "Dados alterados com Sucesso!");
        atualizaTabela();
        limpaCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseClicked
        // TODO add your handling code here:

        linha = tabelaConsulta.getSelectedRow();
        copiaDadosParaOsCampos();  
        carregacapa();
        btnAlterar.setEnabled(true);
    }//GEN-LAST:event_tabelaConsultaMouseClicked

    private void tabelaConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaConsultaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaConsultaMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilenameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        alteracapa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtfilename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilename1ActionPerformed

    public void atualizaTabela() {
        DefaultTableModel model = (DefaultTableModel) tabelaConsulta.getModel();
        ArrayList<hqs> arrConsulta = usuarioDAO.listar();
        int numRows = arrConsulta.size();
        model.setNumRows(numRows);

        for (int i = 0; i < numRows; i++) {
            model.setValueAt(arrConsulta.get(i).getId(), i, 0);
            model.setValueAt(arrConsulta.get(i).getTitulo(), i, 1);
            model.setValueAt(arrConsulta.get(i).getEditora(), i, 2);
            model.setValueAt(arrConsulta.get(i).getAutor(), i, 3);
            model.setValueAt(arrConsulta.get(i).getPaginas(), i, 4);
            model.setValueAt(arrConsulta.get(i).getVolume(), i, 5);
            model.setValueAt(arrConsulta.get(i).getGenero(), i, 6);
            model.setValueAt(arrConsulta.get(i).getCapa(), i, 7);
        }
    }

    public void limpaCampos() {
        txtTitulo.setText("");
        txtEditora.setText("");
        txtAutor.setText("");
        txtPaginas.setText("");
        txtVolume.setText("");
        txtGenero.setText("");
        lblcapa1.setIcon(null);
    }
    
    public void alteracapa(){
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txtfilename1.setText(filename);
        ImageIcon icon = new ImageIcon(filename);
        lblcapa1.setIcon(icon);
    }
    
    public void carregacapa(){
        String filename = (String)tabelaConsulta.getValueAt(linha, 7);
        ImageIcon icon = new ImageIcon(filename); 
        lblcapa1.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblCPF2;
    private javax.swing.JLabel lblCPF3;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblcapa;
    private javax.swing.JLabel lblcapa1;
    private javax.swing.JTable tabelaConsulta;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVolume;
    private javax.swing.JTextField txtfilename;
    private javax.swing.JTextField txtfilename1;
    // End of variables declaration//GEN-END:variables
}
